name: Node CI

on: [push]

jobs:
  hello_osreport_c:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vprufus7/ac-nesrom-gen:latest
      options: --cpus 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build hello_osreport_c
        run: make 
        working-directory: ./hello_osreport_c
      - name: Build debug_printf_c
        run: make 
        working-directory: ./debug_printf_c
      - name: Archive .gci files
        uses: actions/upload-artifact@v3
        with:
          name: gci-files
          path: |
            */*.gci
      