name: Node CI

on: [push]

jobs:
  hello_osreport_c:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vprufus7/ac-nesrom-gen:latest
      volumes:
        - ./hello_osreport_c:/hello_osreport_c
      options: --cpus 1
    steps:
      - name: Build
        run: make 
        working-directory: /hello_osreport_c
      - name: Archive .gci files
        uses: actions/upload-artifact@v3
        with:
          name: gci-files
          path: |
            */*.gci
      